### ISSUE TITLE
Testing failing unexplicably

### ISSUE THREAD

**Issue by vsmagalhaes** [casangi/astrohack#215]
Tests stopped working from one day to another and fail even on commits that were previously successful, leading me to believe that something has changed on the github side.
I have ran all the tests on my two machines using the four supported python versions and they don't fail...

**Comment by jrhosk** [comment]
This is caused by the autorestrictor plugin that is used in the client. We should (and I have) restrict the dask version until the plugin is updated to work with the bleeding edge dask releases; they currently have removed one of the functions that is used in the plugin. Dask is now capped at v2023.12.0.
