### ISSUE TITLE
Graph creation factorization

### ISSUE THREAD

**Issue by vsmagalhaes** [casangi/astrohack#70]
The objective of this issue is to standardize the usage of dask graphs similar in spirit to what has been done with 
function _generate_antenna_ddi_graph_and_compute.
Functions that need to be ported:

- [ ]  extract_holog
   - [ ]  _extract_pointing
   - [ ]  _extract_holog
- [ ] holog

**Comment by jrhosk** [comment]
The functions to do this are included in the linked branch. They just need to be implemented into the actual functions.

**Comment by jrhosk** [comment]
Looking at this a bit more, I have a few comments. Maybe things you already thought of. Firstly, the _holog_chunk is easy enough, no worries there really but in the case of extract_holog the pointing code is already inside the graph associated with extract_holog. The real issue is extract_holog, the loops that submits the code are quite a bit different; different variable to loop over are fine, the problem comes with the way JW rebuilds sections of the input dictionary within the loops. I think this is different enough that it would require a whole other function but we don't need to write a function for a single instance, we should avoid this, so I move we ignore extract_holog as special case.

My plan is to make a generalized build-compute function that works on both hack files and general, user supplied loops. I think this will be much more useful and if achieved could be used throughout the code, especially if we write code with the input structure in mind.
